In [1]:
import random
import os

from scipy.ndimage import imread
from scipy.misc import imsave
import numpy as np
from scipy.signal import resample
from scipy import ndimage as nd
import pandas as pd
import matplotlib.pyplot as plt

import tools
from config import config as c

Using TensorFlow backend.


In [2]:
train_gen, test_gen = tools.get_generators(c)

In [3]:
for i in range(30):
    b = next(train_gen)

/media/nazar/DATA/ARVI_course/arvi_projects/week3/tools.py:187: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  au = pd.read_csv(label, delimiter='   ', names=['emotion', 'value'])


Found 0 faces on image. Path S065/003
Found 0 faces on image. Path S074/005
Found 0 faces on image. Path S112/001
Found 0 faces on image. Path S052/002


In [5]:
img_inputs = b[0]['img_inputs'].squeeze()
print(img_inputs.shape)
landmark_inputs = b[0]['landmark_inputs']
out_emotion = b[1]['out_emotion']
out_au = b[1]['out_au']

(2, 20, 240, 320)


In [6]:
img_inputs = ((img_inputs + 1) * 127.5).astype(np.uint8)
img_inputs = img_inputs[0]
_ = [imsave('./resampled_{}.png'.format(i), img) for i, img in enumerate(img_inputs)]

In [7]:
out_emotion

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
out_au

array([[ 1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.]])

In [9]:
landmark_inputs

array([[[-1.1       ,  0.14      , -1.1       , ...,  0.98      ,
         -0.08      ,  0.96      ],
        [-1.06842208,  0.14703056, -1.06842208, ...,  0.97040171,
         -0.06861426,  0.95079763],
        [-1.06842208,  0.12742649, -1.06842208, ...,  0.97040171,
         -0.06861426,  0.95079763],
        ..., 
        [-1.06842208,  0.10782241, -1.06842208, ...,  1.08802616,
         -0.10782241,  1.06842208],
        [-1.04901961,  0.07843137, -1.04901961, ...,  1.09803922,
         -0.12745098,  1.07843137],
        [-1.05978806,  0.069986  , -1.07978406, ...,  1.12977407,
         -0.13997201,  1.10977807]],

       [[-1.03460398,  0.17437146, -1.01135446, ...,  1.03460398,
         -0.03487429,  1.01135446],
        [-1.05785351,  0.15112193, -1.01135446, ...,  1.01135446,
         -0.03487429,  1.01135446],
        [-1.03460398,  0.15112193, -1.01135446, ...,  1.03460398,
         -0.03487429,  1.01135446],
        ..., 
        [-1.03376614,  0.1858456 , -0.98730474, ...,